version: '2'
services:
    stidm-app:
        image: stidm
        external_links:
            - stidm-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=STIDM
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    stidm-mongodb:
        extends:
            file: mongodb.yml
            service: stidm-mongodb
