version: '2'
services:
    stidm-mongodb:
        container_name: stidm-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/STIDM/mongodb/:/data/db/
